---
name: pswslmanage
on: 
  push:
  # pull_request:
  #   branches:
  #     - dev

jobs:
  pwslmanage:
    name: pswslmanage
    runs-on: [self-hosted]
    permissions:
      actions: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print all variables
        run: |
          dir env:

      - name: PSScriptAnalyzer
        run: |
          echo "-------------"
          echo "${{ vars.GITHUB_WORKSPACE }} - foobar"
          echo "$GH_WORKDIR - foobar"
          echo "-------------"
          $_issue_list=$null
          $_issue_list=@()
          foreach($_issue in $(Invoke-ScriptAnalyzer ${{ runner.temp }}\pswslmanage.psm1)) {Write-Output "Add issue"; $_issue_list += $_issue}
          foreach($_issue in $(Invoke-ScriptAnalyzer ${{ runner.temp }}\pswslmanage-roles.ps1)) {Write-Output "Add issue"; $_issue_list += $_issue}
          foreach($_issue in $(Invoke-ScriptAnalyzer ${{ runner.temp }}\pswslmanage-helper.ps1)) {Write-Output "Add issue"; $_issue_list += $_issue}
          if($_issue_list.Count -gt 0) {$_issue_list; Write-Error "Linter issues found. Exiting"} 
        env:
          GH_WORKDIR: "testabc"

      - name: Publish
        run: |
          $_user = "${{ github.actor }}"
          $_token = "${{ github.token }}" | ConvertTo-SecureString -AsPlainText -Force
          $_creds = New-Object System.Management.Automation.PSCredential -ArgumentList @($_user, $_token)
          $_feed = "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          $_module_name = "pswslmanage"
          $_repository_name = "PowershellNugetServices"
          
          $_drop_path = "${{ runner.temp }}"
          $_module_path = [System.IO.Path]::GetFullPath((Join-Path -Path $_drop_path -ChildPath $_module_name))
          
          ## Force TLS1.2
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          
          ## Register repository
          $_args = @{
              Name = $_repository_name
              SourceLocation = $_feed
              PublishLocation = $_feed
              InstallationPolicy = 'Trusted'
              Credential = $_creds
          }
          
          Register-PSRepository @_args
          
          Publish-Module -Path $_module_path `
            -Repository $_repository_name `
            -NuGetApiKey "${{ github.token }}"
  