---
name: sa-pswslmanage-dev
on: workflow_dispatch
  #push
  # pull_request:
  #   branches:
  #     - dev

jobs:
  sa-pswslmanage-dev:
    name: sa-pswslmanage-dev
    runs-on: [self-hosted]
    permissions:
      actions: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./pswslmanage

      - name: Print variables
        run: |
          dir env:
        shell: pwsh

      - name: Execute PSScriptAnalyzer
        run: |
          $_repo_dir = "{0}\shiftavenue-pswslmanage\pswslmanage" -f $($env:RUNNER_WORKSPACE)
          $_issue_list=$null
          $_issue_list=@()
          echo "Working directory for script analyzer: $_repo_dir"
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -AllowClobber -Scope CurrentUser -ErrorAction SilentlyContinue
          Import-Module PSScriptAnalyzer -ErrorAction SilentlyContinue
          Set-PSRepository PSGallery -InstallationPolicy Untrusted
          foreach($_issue in $(Invoke-ScriptAnalyzer -Path "$_repo_dir\pswslmanage.psm1")) {Write-Output "Add issue"; $_issue_list += $_issue}
          foreach($_issue in $(Invoke-ScriptAnalyzer -Path "$_repo_dir\pswslmanage-roles.ps1")) {Write-Output "Add issue"; $_issue_list += $_issue}
          foreach($_issue in $(Invoke-ScriptAnalyzer -Path "$_repo_dir\pswslmanage-helper.ps1")) {Write-Output "Add issue"; $_issue_list += $_issue}
          if($_issue_list.Count -gt 0) {$_issue_list; Write-Error "Linter issues found. Exiting"}
        shell: pwsh

      - name: Create manifest
        run: |
          $_repo_dir = "{0}\shiftavenue-pswslmanage\pswslmanage" -f $($env:RUNNER_WORKSPACE)
          Remove-Item -Path "$_repo_dir\pswslmanage.psd1" -Force
          New-ModuleManifest -Path "$_repo_dir\pswslmanage.psd1" `
                              -ModuleVersion "1.0.$($env:GITHUB_RUN_NUMBER)" `
                              -Author "David Koenig" `
                              -Guid "a2d16567-94f2-4a76-8e0d-c29d40177c56" `
                              -CompatiblePSEditions Core `
                              -PowerShellVersion 7.3 `
                              -CompanyName "shiftavenue" `
                              -Copyright "(c) shiftavenue. All rights reserved." `
                              -RootModule "pswslmanage.psm1" `
                              -Description "With this module you can install and maintain WSL images" `
                              -ProcessorArchitecture Amd64 `
                              -FunctionsToExport @("Add-WslImage", "Test-WslImage", "Get-WslImage", "Remove-WslImage", "Stop-WslImage", "Add-WslUser", "Add-WslRoleSSH" ) `
                              -Tags "wsl,windows,linux,wsl2" `
                              -ProjectUri "https://github.com/shiftavenue/shiftavenue-pswslmanage" `
                              -IconUri "https://raw.githubusercontent.com/shiftavenue/shiftavenue-pswslmanage/main/Icon.png" `
                              -Prerelease "dev$($env:GITHUB_RUN_NUMBER)"
        shell: pwsh

      - name: Publish
        run: |
          $_repo_name = "PSGallery"
          $_token = $($env:PUBLISH_TOKEN)
          $_module_name = "pswslmanage"
          $_repo_dir = "{0}\shiftavenue-pswslmanage\pswslmanage" -f $($env:RUNNER_WORKSPACE)

          echo "-----------------"
          echo "repo_name:   $_repo_name"
          echo "repo_dir:    $_repo_dir"
          echo "-----------------"

          $_local_nuget_path = "{0}\Microsoft\Windows\PowerShell\PowerShellGet" -f $($env:LOCALAPPDATA)
          if (-Not (Test-Path -Path $_local_nuget_path)) {New-Item -Path $_local_nuget_path -ItemType Directory -Force}
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://aka.ms/psget-nugetexe" -OutFile "$_local_nuget_path\nuget.exe"

          echo "Publish the package"
          Publish-Module -Path "$_repo_dir" -Repository "$_repo_name" -NuGetApiKey "$_token" -Verbose
        env:
          PUBLISH_TOKEN: ${{secrets.PSGALLERY_API_KEY}}
        shell: pwsh