---
name: pswslmanage
on: push
jobs:
  pwslmanage:
    name: pswslmanage
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo_pswslmanage
      
      - name: Run powershell linter again valid module files
        run: |
          $_issue_list=@()
          foreach($_issue in $(Invoke-ScriptAnalyzer .\pswslmanage.psm1)) {$_issue_list += $_issue}
          foreach($_issue in $(Invoke-ScriptAnalyzer .\pswslmanage-roles.ps1)) {$_issue_list += $_issue}
          foreach($_issue in $(Invoke-ScriptAnalyzer .\pswslmanage-helper.ps1)) {$_issue_list += $_issue}
          if($_issue_list.Count -gt 0) {$_issue_list; Write-Error "Linter issues found. Exiting"} 