---
name: pswslmanage
on: push
jobs:
  pwslmanage:
    name: pswslmanage
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: repo_pswslmanage
      
      - name: Run powershell linter again valid module files
        run: |
          Invoke-ScriptAnalyzer "${{ vars.GITHUB_WORKSPACE }}\pswslmanage.psm1"
          Invoke-ScriptAnalyzer "${{ vars.GITHUB_WORKSPACE }}\pswslmanage-roles.ps1"
          Invoke-ScriptAnalyzer "${{ vars.GITHUB_WORKSPACE }}\pswslmanage-helper.ps1"
